/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as TierkommunikationRouteImport } from './routes/tierkommunikation'
import { Route as SelbstfindungRouteImport } from './routes/selbstfindung'
import { Route as RechtlichesRouteImport } from './routes/rechtliches'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as HaltungRouteImport } from './routes/haltung'
import { Route as AngeboteRouteImport } from './routes/angebote'
import { Route as IndexRouteImport } from './routes/index'

const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const TierkommunikationRoute = TierkommunikationRouteImport.update({
  id: '/tierkommunikation',
  path: '/tierkommunikation',
  getParentRoute: () => rootRouteImport,
} as any)
const SelbstfindungRoute = SelbstfindungRouteImport.update({
  id: '/selbstfindung',
  path: '/selbstfindung',
  getParentRoute: () => rootRouteImport,
} as any)
const RechtlichesRoute = RechtlichesRouteImport.update({
  id: '/rechtliches',
  path: '/rechtliches',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const HaltungRoute = HaltungRouteImport.update({
  id: '/haltung',
  path: '/haltung',
  getParentRoute: () => rootRouteImport,
} as any)
const AngeboteRoute = AngeboteRouteImport.update({
  id: '/angebote',
  path: '/angebote',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/haltung': typeof HaltungRoute
  '/kontakt': typeof KontaktRoute
  '/rechtliches': typeof RechtlichesRoute
  '/selbstfindung': typeof SelbstfindungRoute
  '/tierkommunikation': typeof TierkommunikationRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/haltung': typeof HaltungRoute
  '/kontakt': typeof KontaktRoute
  '/rechtliches': typeof RechtlichesRoute
  '/selbstfindung': typeof SelbstfindungRoute
  '/tierkommunikation': typeof TierkommunikationRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/haltung': typeof HaltungRoute
  '/kontakt': typeof KontaktRoute
  '/rechtliches': typeof RechtlichesRoute
  '/selbstfindung': typeof SelbstfindungRoute
  '/tierkommunikation': typeof TierkommunikationRoute
  '/ueber-mich': typeof UeberMichRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/angebote'
    | '/haltung'
    | '/kontakt'
    | '/rechtliches'
    | '/selbstfindung'
    | '/tierkommunikation'
    | '/ueber-mich'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/angebote'
    | '/haltung'
    | '/kontakt'
    | '/rechtliches'
    | '/selbstfindung'
    | '/tierkommunikation'
    | '/ueber-mich'
  id:
    | '__root__'
    | '/'
    | '/angebote'
    | '/haltung'
    | '/kontakt'
    | '/rechtliches'
    | '/selbstfindung'
    | '/tierkommunikation'
    | '/ueber-mich'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngeboteRoute: typeof AngeboteRoute
  HaltungRoute: typeof HaltungRoute
  KontaktRoute: typeof KontaktRoute
  RechtlichesRoute: typeof RechtlichesRoute
  SelbstfindungRoute: typeof SelbstfindungRoute
  TierkommunikationRoute: typeof TierkommunikationRoute
  UeberMichRoute: typeof UeberMichRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierkommunikation': {
      id: '/tierkommunikation'
      path: '/tierkommunikation'
      fullPath: '/tierkommunikation'
      preLoaderRoute: typeof TierkommunikationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selbstfindung': {
      id: '/selbstfindung'
      path: '/selbstfindung'
      fullPath: '/selbstfindung'
      preLoaderRoute: typeof SelbstfindungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtliches': {
      id: '/rechtliches'
      path: '/rechtliches'
      fullPath: '/rechtliches'
      preLoaderRoute: typeof RechtlichesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haltung': {
      id: '/haltung'
      path: '/haltung'
      fullPath: '/haltung'
      preLoaderRoute: typeof HaltungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebote': {
      id: '/angebote'
      path: '/angebote'
      fullPath: '/angebote'
      preLoaderRoute: typeof AngeboteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngeboteRoute: AngeboteRoute,
  HaltungRoute: HaltungRoute,
  KontaktRoute: KontaktRoute,
  RechtlichesRoute: RechtlichesRoute,
  SelbstfindungRoute: SelbstfindungRoute,
  TierkommunikationRoute: TierkommunikationRoute,
  UeberMichRoute: UeberMichRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
